spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# Connection url dynamically constructed from environment variables
spring.datasource.url = jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:UserDB}?useSSL=false&allowPublicKeyRetrieval=true

# Username and password loaded dynamically at runtime
spring.datasource.username = ${DB_USERNAME:root}
spring.datasource.password = ${DB_PASSWORD:root}

